name: LapawaDe
description: ""

markdown: kramdown
highlighter: rouge

gems:
 - jekyll-mentions

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"

