name: LapawaDe
description: ""

markdown: kramdown
pygments: true

gems:
 - jekyll-mentions

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

